---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

安裝套件
```{r}
install.packages("stringr")
```

引入套件
```{r}
library(stringr)
```

#subset

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
course
str_subset(course,"經濟學")
```

```{r}
course
str_detect(course,"經濟學")
```

```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
studentID
系別<-str_sub(studentID,5,6)
系別
入學年<-str_sub(studentID,2,4)
入學年
```

#join

str_c
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```

```{r}
str_c(month,c("月"),day,c("日"))
str_c(month,"月",day,"日")
```

```{r}
month
day
str_c(month,day, sep="-")
```

#split

```{r}
dates <- c("3-11", "4-5",  "2-7")
dates
str_split(dates,"-")
```

#replace

str_replace
```{r}
dates
str_replace(dates,"-","月")
```

str_replace_all
```{r}
dates2 <- c("3-11-2019", "4-5-2017",  "2-7-2015")
dates2
str_replace(dates2,"-","/")
str_replace_all(dates2,"-","/")
```

練習
```{r}
library(readr)
githubData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/githubData.csv")
username <- githubData$`GitHub username`[11:16]
reponame <- githubData$`GitHub repo name`[11:16]
```

```{r}
str_c("https://github.com/",username,"/",reponame)
str_c("https://github.com",username,reponame,sep="/")
```

練習一
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/%E7%AC%AC%E4%B8%89%E5%B1%86%E7%B6%93%E6%BF%9F%E6%92%AD%E5%AE%A2%E7%AB%B6%E8%B3%BD%E5%8F%83%E8%B3%BD%E4%BD%9C%E5%93%81%E6%8A%95%E7%A5%A8%E7%B5%90%E6%9E%9C%E6%A8%A3%E6%9C%AC%20-%20Sheet1.csv")
birthday<-filmVotingData$`出生西元年月日（驗證本人用）`
```

```{r}
head(birthday)

byear <- str_sub(birthday,1,4)
bmonth <- str_sub(birthday,5,6)
bday <- str_sub(birthday,7,8)
str_c("西元",byear,"年",bmonth,"月",bday,"日")
```

練習二
```{r}
民國年月<-c("099/01","099/02","099/03")
```

```{r}
y <- str_sub(民國年月,1,3)
m <- str_sub(民國年月,5,6)
y2 <- as.integer(y)
y3 <- as.character(y2+1911)
西元年月 <- str_c(y3,m,sep="/")
西元年月
```

# vectors

```{r}
a<-c(1:3) # a <- c(1,2,3)
typeof(a)
a
```

```{r}
aWithNames <- c(
  a1=1,
  a2=2,
  a3=3
)
typeof(aWithNames)
aWithNames
```

