---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# function usage
```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}
```

```{r}
utility_cobb_douglass(1,2,0.5,0.8)

utility_cobb_douglass(1,2,.beta=0.8,.alpha=0.5)
utility_cobb_douglass(1,.beta=0.8,2,0.5)
utility_cobb_douglass(1,.beta=0.8,.alpha=0.5,2)
utility_cobb_douglass(.alpha=0.5,.beta=0.8,y=2,x=1)
```

# iteration
```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
```

```{r}
studentIds <- unique(transcriptDataFinal$學號) # 全部可能學號
```

sequence_source
```{r}
# 以前5筆學號為sequence_source
studentIds5 <- studentIds[1:5] # 前5筆學號
studentIds5
```

作法一
```{r}
for(i in studentIds5){ 
  print(i) # 印出studentIds5[[i]]
}
```

```{r}
gpa_fun(studentIds5[[1]])
for(i in studentIds5){
  print(i)
  print(gpa_fun(i))
}  
```

作法二
```{r}
c(1:5)
```

```{r}
for(i in c(1:5)){ 
  print(i) 
}
```

```{r}
for(i in c(1:5)){ 
  print(i) 
  print(studentIds5[[i]])
}
```

seq_along()
```{r}
seq_along(studentIds5)
```

```{r}
for(i in seq_along(studentIds5)){
  print(i)
  print(studentIds5[[i]])
}
```

##範例二
```{r}
gmailAddress <- c(
  "tim@gmail.com",
  "anita",
  "yellen@gmail.com",
  "huang@gmail.com"
)
```

```{r}
# 作法一
for (i in gmailAddress) {
  print(i)
}
```

```{r}
# 作法二
for (i in c(1:4)) {
  print(i)
  print(gmailAddress[[i]])
}
```

```{r}
# 作法三
for (i in seq_along(gmailAddress)) {
  print(i)
  print(gmailAddress[[i]])
}
```

一、
```{r}
library(stringr)

for(i in gmailAddress){ 
  if(str_detect(gmailAddress,"@gmail.com")){
    print(i)
  } else {
    str_c(gmailAddress,"@gmail.com")
    print(i) 
  }
}
```
二、
```{r}
for(i in c(1:4)){ 
  if(str_detect(gmailAddress,"@gmail.com")){
    print(i)
  } else {
    str_c(gmailAddress,"@gmail.com")
    print(i) 
  } 
}
```
三、
```{r}
for(i in seq_along(gmailAddress)){
  if(str_detect(gmailAddress,"@gmail.com")){
    print(i)
  } else {
    str_c(gmailAddress,"@gmail.com")
    print(i) 
  } 
}
```

